CREATE DATABASE IF NOT EXISTS ticweb_a11y;

USE ticweb_a11y;

DROP TABLE IF EXISTS pages;
CREATE TABLE IF NOT EXISTS pages(
  id int(10) NOT NULL AUTO_INCREMENT,
  url varchar(10000) NOT NULL DEFAULT '',
  date DATE NOT NULL, 
  last_modified DATE DEFAULT NULL,
  error BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

GRANT ALL PRIVILEGES ON *.* TO 'ticweb'@'localhost' IDENTIFIED BY 'K4RN4Vu' ;
GRANT ALL PRIVILEGES ON *.* TO 'ticweb'@'%' IDENTIFIED BY 'K4RN4Vu';
FlUSH PRIVILEGES;
